export const SEARCH_REPOS_SUCCEEDED = 'SEARCH_REPOS_SUCCEEDED';
export const FETCH_BRANCHES_SUCCEEDED = 'FETCH_BRANCHES_SUCCEEDED';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const TOGGLE_PRELOADER = 'TOGGLE_PRELOADER';
export const RESET_BRANCHES = 'RESET_BRANCHES';
